app:
  name: springboot-jwt

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: mariorossi
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: ERROR
    it.imperato: DEBUG
